//! Manifest-vs-source consistency: the SAME dbt project loaded both ways must
//! produce the same `Dag`.
//!
//! `tests/fixtures/sample_manifest.json` is generated by REAL dbt
//! (`make regen-sample-manifest` → `dbt parse` with dbt-duckdb) from
//! `tests/fixtures/sample_project/`, so these tests are an executable contract
//! against dbt's actual semantics — not our model of them. If the source
//! loader's parsing drifts from what dbt does (comment handling, config
//! precedence, the project config tree, disabled nodes, test capture), a
//! comparison here breaks.
//!
//! Documented, deliberate differences (excluded from comparison):
//! - `NodeDetail.database` / `.schema` for models/seeds/snapshots: dbt fills
//!   them from the *profile* (connection), which source mode cannot know.
//!   Source nodes compare fully — their schema/database come from schema.yml.
//! - Seed `columns`: dbt only records them when documented in a schema file;
//!   source mode additionally reads the CSV header (a strict superset of
//!   information, surfaced in the structure modal).
//! - Test *names*: dbt mints hashed unique names; tests are compared as
//!   (kind, column) multisets per node, which is exactly what the UI shows.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use dbtl::{build_model_list, layout, load_dag, load_dag_from_source, Dag, NodeInfo, SortMode};

const MANIFEST: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/sample_manifest.json"
);
const PROJECT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/sample_project");

/// (manifest-mode Dag, source-mode Dag) of the same project.
fn dags() -> (Dag, Dag) {
    assert!(
        Path::new(MANIFEST).is_file(),
        "fixture missing — run `make regen-sample-manifest`"
    );
    let from_manifest = load_dag(MANIFEST).expect("sample manifest loads");
    let from_source = load_dag_from_source(PROJECT).expect("sample project parses");
    (from_manifest, from_source)
}

/// All node infos keyed by uid, in a deterministic map.
fn node_map(dag: &Dag) -> BTreeMap<String, NodeInfo> {
    dag.nodes()
        .iter()
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect()
}

#[test]
fn node_sets_and_infos_are_identical() {
    // The strongest single check: every NodeInfo field — unique_id, name,
    // resource_type, path, materialized, direct_up/down (edge degrees), and
    // test_count — must agree for every node. This covers the config
    // precedence chain, the project tree, disabled-node dropping, and the
    // comment semantics in one comparison.
    let (m, s) = dags();
    let mm = node_map(&m);
    let sm = node_map(&s);
    let m_ids: BTreeSet<&String> = mm.keys().collect();
    let s_ids: BTreeSet<&String> = sm.keys().collect();
    assert_eq!(
        m_ids, s_ids,
        "node id sets diverge between manifest and source modes"
    );
    for (uid, mi) in &mm {
        assert_eq!(
            mi, &sm[uid],
            "NodeInfo diverges for {uid} (manifest vs source)"
        );
    }
}

#[test]
fn full_lineage_closures_are_identical() {
    // Same transitive upstream/downstream closure for every node — i.e. the
    // pruned adjacency is the same graph, not merely the same degrees.
    let (m, s) = dags();
    for uid in node_map(&m).keys() {
        assert_eq!(m.upstream(uid), s.upstream(uid), "upstream({uid}) diverges");
        assert_eq!(
            m.downstream(uid),
            s.downstream(uid),
            "downstream({uid}) diverges"
        );
    }
}

#[test]
fn details_are_identical_modulo_profile_data() {
    let (m, s) = dags();
    for (uid, info) in node_map(&m) {
        let md = m.detail(&uid).expect("manifest detail");
        let sd = s.detail(&uid).expect("source detail");
        assert_eq!(md.materialized, sd.materialized, "{uid} materialized");
        assert_eq!(md.description, sd.description, "{uid} description");
        assert_eq!(md.tags, sd.tags, "{uid} tags");
        assert_eq!(
            md.original_file_path, sd.original_file_path,
            "{uid} original_file_path"
        );
        // database/schema come from the PROFILE for non-sources (unknowable
        // without a connection); sources carry them in schema.yml — compare.
        if info.resource_type == "source" {
            assert_eq!(md.schema, sd.schema, "{uid} schema");
            assert_eq!(md.database, sd.database, "{uid} database");
        }
        // Seed columns: source mode reads the CSV header dbt doesn't record.
        if info.resource_type != "seed" {
            assert_eq!(md.columns, sd.columns, "{uid} columns");
        }
    }
}

#[test]
fn seed_columns_are_a_source_mode_superset() {
    // The one deliberate enrichment: dbt's manifest has no columns for an
    // undocumented seed; source mode surfaces the CSV header instead.
    let (m, s) = dags();
    let uid = "seed.sample.country_codes";
    assert!(
        m.detail(uid).unwrap().columns.is_empty(),
        "dbt records no columns for an undocumented seed"
    );
    let cols: Vec<&str> = s
        .detail(uid)
        .unwrap()
        .columns
        .iter()
        .map(|c| c.name.as_str())
        .collect();
    assert_eq!(cols, vec!["code", "country"], "CSV header columns surfaced");
}

#[test]
fn tests_are_identical_as_kind_column_multisets() {
    // dbt mints hashed test NAMES; the UI shows kind+column, so that is the
    // contract: per-node multisets of (kind, column_name) must match.
    let (m, s) = dags();
    for uid in node_map(&m).keys() {
        let key = |d: &Dag| -> Vec<(String, Option<String>)> {
            let mut v: Vec<_> = d
                .tests(uid)
                .iter()
                .map(|t| (t.kind.clone(), t.column_name.clone()))
                .collect();
            v.sort();
            v
        };
        assert_eq!(key(&m), key(&s), "tests diverge for {uid}");
    }
}

#[test]
fn exposures_are_identical_including_payload() {
    // Exposures ride the same NodeInfo/closure comparisons as every other node
    // (node_sets / closures tests above); this pins the exposure-ONLY surface:
    // the side-map payload (kind / owner / url) and the terminator contract.
    let (m, s) = dags();
    let exp_ids: Vec<String> = node_map(&m)
        .keys()
        .filter(|k| k.starts_with("exposure."))
        .cloned()
        .collect();
    assert_eq!(exp_ids.len(), 2, "sample project declares two exposures");
    for uid in &exp_ids {
        let mp = m.exposure(uid).expect("manifest-mode payload");
        let sp = s.exposure(uid).expect("source-mode payload");
        assert_eq!(mp, sp, "exposure payload diverges for {uid}");
        assert!(
            m.downstream(uid).is_empty() && s.downstream(uid).is_empty(),
            "{uid} must be a terminator leaf in both modes"
        );
        assert!(
            !m.upstream(uid).is_empty(),
            "{uid} depends on at least one kept node"
        );
    }
    // Spot-check the full payload once (the dashboard exposure).
    let dash = m
        .exposure("exposure.sample.orders_dashboard")
        .expect("dashboard payload");
    assert_eq!(dash.exposure_type.as_deref(), Some("dashboard"));
    assert_eq!(dash.owner_name.as_deref(), Some("Finance Team"));
    assert_eq!(dash.owner_email.as_deref(), Some("finance@example.com"));
    assert_eq!(
        dash.url.as_deref(),
        Some("https://bi.example.com/dashboards/42")
    );
    // And the minimal one: no email / url, still typed and owned.
    let nb = m
        .exposure("exposure.sample.churn_notebook")
        .expect("notebook payload");
    assert_eq!(nb.exposure_type.as_deref(), Some("notebook"));
    assert_eq!(nb.owner_name.as_deref(), Some("Analytics"));
    assert_eq!(nb.owner_email, None);
    assert_eq!(nb.url, None);
}

#[test]
fn model_list_and_lineage_render_identically() {
    // End-to-end: the left pane grouping and a full lineage CharGrid render are
    // byte-identical across modes (follows from Dag equality + determinism, but
    // this is the user-visible surface, so pin it directly).
    let (m, s) = dags();
    let ml = build_model_list(&m, SortMode::Layer);
    let sl = build_model_list(&s, SortMode::Layer);
    let groups = |l: &dbtl::ModelList| -> Vec<(String, Vec<String>)> {
        l.groups
            .iter()
            .map(|g| {
                (
                    g.layer.clone(),
                    g.models.iter().map(|n| n.name.clone()).collect(),
                )
            })
            .collect()
    };
    assert_eq!(groups(&ml), groups(&sl), "left-pane grouping diverges");

    // EVERY node's full lineage render (the project is tiny, so exhaustive is
    // cheap) — catches anything that escaped the structural comparisons but
    // would still show up on screen (tags, tests labels, box widths).
    for uid in node_map(&m).keys() {
        let m_lay = layout(&m.subgraph(uid));
        let s_lay = layout(&s.subgraph(uid));
        assert_eq!(
            m_lay.grid.to_text(),
            s_lay.grid.to_text(),
            "lineage render diverges for {uid}"
        );
        assert_eq!(
            m_lay.grid.emphasis_regions(),
            s_lay.grid.emphasis_regions(),
            "emphasis diverges for {uid}"
        );
    }
}
