//! CLI-level coverage for the `dbtl docs` subcommand: the parts that live in
//! `main.rs` (not the pure `dbtl::generate_docs`) — the `--quiet` stdout
//! suppression and end-to-end determinism on disk.
//!
//! These shell out to the built binary (Cargo exposes its path via
//! `CARGO_BIN_EXE_dbtl`), so they exercise the real argument parsing + IO path
//! without ever touching a TTY (the `docs` subcommand returns before any
//! terminal init, like `--list-themes`).

use std::path::PathBuf;
use std::process::Command;

/// The frozen fixture manifest the rest of the suite pins.
fn fixture_manifest() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("manifest.json")
}

/// A unique temp output dir under the OS temp root (PID + a label keep parallel
/// test runs from colliding). Created fresh by the binary.
fn temp_out(label: &str) -> PathBuf {
    std::env::temp_dir().join(format!("dbtl_docs_cli_{}_{}", std::process::id(), label))
}

fn run_docs(out: &PathBuf, quiet: bool) -> std::process::Output {
    let mut cmd = Command::new(env!("CARGO_BIN_EXE_dbtl"));
    cmd.arg("docs")
        .arg("--manifest")
        .arg(fixture_manifest())
        .arg("--out")
        .arg(out);
    if quiet {
        cmd.arg("--quiet");
    }
    cmd.output().expect("failed to run dbtl docs")
}

#[test]
fn docs_succeeds_and_prints_summary_without_quiet() {
    let out = temp_out("loud");
    let _ = std::fs::remove_dir_all(&out);
    let result = run_docs(&out, false);
    assert!(result.status.success(), "docs should exit 0");
    let stdout = String::from_utf8_lossy(&result.stdout);
    assert!(
        stdout.contains("wrote") && stdout.contains("files"),
        "non-quiet run prints a summary, got: {stdout:?}"
    );
    assert!(out.join("README.md").is_file(), "README.md was written");
    let _ = std::fs::remove_dir_all(&out);
}

#[test]
fn quiet_suppresses_stdout_but_still_writes_files() {
    let out = temp_out("quiet");
    let _ = std::fs::remove_dir_all(&out);
    let result = run_docs(&out, true);
    assert!(result.status.success(), "quiet docs should still exit 0");
    assert!(
        result.stdout.is_empty(),
        "--quiet must produce no stdout, got: {:?}",
        String::from_utf8_lossy(&result.stdout)
    );
    assert!(
        out.join("README.md").is_file(),
        "files are still written under --quiet"
    );
    let _ = std::fs::remove_dir_all(&out);
}

#[test]
fn quiet_and_loud_write_identical_files() {
    // The `--quiet` flag changes ONLY stdout, never the generated bytes —
    // so the on-disk doc set is identical either way (the determinism contract
    // CI relies on).
    let loud = temp_out("det_loud");
    let quiet = temp_out("det_quiet");
    let _ = std::fs::remove_dir_all(&loud);
    let _ = std::fs::remove_dir_all(&quiet);
    assert!(run_docs(&loud, false).status.success());
    assert!(run_docs(&quiet, true).status.success());

    let readme_loud = std::fs::read(loud.join("README.md")).expect("loud README");
    let readme_quiet = std::fs::read(quiet.join("README.md")).expect("quiet README");
    assert_eq!(
        readme_loud, readme_quiet,
        "README bytes identical regardless of --quiet"
    );

    // And the same file set.
    let names = |dir: &PathBuf| {
        let mut v: Vec<String> = std::fs::read_dir(dir.join("models"))
            .expect("models dir")
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .collect();
        v.sort();
        v
    };
    assert_eq!(names(&loud), names(&quiet), "same node-page file set");

    let _ = std::fs::remove_dir_all(&loud);
    let _ = std::fs::remove_dir_all(&quiet);
}

#[test]
fn missing_data_source_fails_with_nonzero_exit_and_stderr() {
    // Pointing `--project` at a dir with no manifest and no dbt_project.yml is a
    // load failure: plain-text stderr + non-zero exit, no panic, no TTY.
    let empty = temp_out("empty_project");
    std::fs::create_dir_all(&empty).expect("create empty project dir");
    let out = temp_out("err_out");
    let result = Command::new(env!("CARGO_BIN_EXE_dbtl"))
        .arg("docs")
        .arg("--project")
        .arg(&empty)
        .arg("--out")
        .arg(&out)
        .output()
        .expect("failed to run dbtl docs");
    assert!(!result.status.success(), "missing source should fail");
    let stderr = String::from_utf8_lossy(&result.stderr);
    assert!(
        stderr.contains("error:"),
        "plain-text error on stderr, got: {stderr:?}"
    );
    let _ = std::fs::remove_dir_all(&empty);
    let _ = std::fs::remove_dir_all(&out);
}
